<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>warnings</Nullable>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<WarningLevel>5</WarningLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<Features>strict</Features>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ViewOwl.Config\ViewOwl.Config.csproj" />
	</ItemGroup>

</Project>
